### ISSUE TITLE
Nothing happens on chrome: WebGLRenderer fails to create context

### ISSUE THREAD

**Issue by ghost** [HackGT/hackgt4#3]
# Issue

![deepin-screen-recorder_select area_20170714224754](https://user-images.githubusercontent.com/14112725/28235913-8cfc61a0-68e6-11e7-9612-96fce90b9186.gif)

When I opened the site up it just stayed stuck at the pre-loader; worse, there was a skip button and it didn't work which confused me (because the animation didn't seem to work at all).  Works with Opera as expected.

Here's what the console says:

```
THREE.WebGLRenderer: Error creating WebGL context.
o.WebGLRenderer @ bundle.js:14

Uncaught (in promise) TypeError: Cannot read property 'getExtension' of null
    at o.WebGLExtensions.get (https://hack.gt/bundle.js:15:2930)
    at new o.WebGLRenderer (https://hack.gt/bundle.js:14:20336)
    at new e (https://hack.gt/bundle.js:3:29044)
    at https://hack.gt/bundle.js:3:23424
    at r (https://hack.gt/bundle.js:3:14911)
    at Generator._invoke (https://hack.gt/bundle.js:3:16031)
    at Generator.t.(anonymous function) [as next] (https://hack.gt/bundle.js:3:15090)
    at r (https://hack.gt/bundle.js:3:14911)
    at n (https://hack.gt/bundle.js:3:15146)
    at https://hack.gt/bundle.js:3:15469
```

# Replication

Open Google chrome and navigate to the site.

Tested on [Deepin 15.4](https://www.deepin.org/en/), Chrome Version 58.0.3029.110

**Comment by illegalprime** [comment]
+1 for Deepin

**Comment by illegalprime** [comment]
@Lionex it works for me on Chrome + Arch, do you have any extensions that might be blocking JavaScript? Also what's your chrome version? 

EDIT: I see you version, mine is 56, I'll check it out.

**Comment by ghost** [comment]
No extensions @illegalprime, and Chrome is really passive-aggresive about it.

> ![passive-aggressive-chrome](https://user-images.githubusercontent.com/14112725/28242193-54e223bc-6973-11e7-9171-d2347ffb4cb0.png)

**Comment by illegalprime** [comment]
^ lol, I updated and got to Chrome 59.0.3071.115, still not seeing issues.
If you clone the repo and run `npm install && npm run watch & python3 -m http.server` does the issue still persist? (note the double then single ampersand) The stack trace in the dev version will help us pin down which call is failing.

**Comment by ghost** [comment]
@illegalprime on it, get back to you soon
